### ISSUE TITLE
TypeError: Cannot read property 'get_channel' of null

### ISSUE THREAD

**Issue by mectorfector** [KixAss/homebridge-lgtv-2012a#1]
```
[Homebridge] [4/29/2020, 7:22:02 PM] TypeError: Cannot read property 'get_channel' of null
    at /home/hoobs/.hoobs/node_modules/homebridge-lgtv-2012a/index.js:314:8
    at /home/hoobs/.hoobs/node_modules/homebridge-lgtv-2012a/index.js:223:5
    at lgtv.new_session (/home/hoobs/.hoobs/node_modules/lgtv-2012/index.js:194:20)
    at LGAccessory.connect (/home/hoobs/.hoobs/node_modules/homebridge-lgtv-2012a/index.js:221:12)
    at LGAccessory.getChannel (/home/hoobs/.hoobs/node_modules/homebridge-lgtv-2012a/index.js:313:9)
    at Characteristic.ActiveIdentifier.emit (events.js:310:20)
    at Characteristic.ActiveIdentifier.Characteristic.getValue (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/lib/Accessory.js:735:8)
```

**Comment by mectorfector** [comment]
Thank you for this great plugin. I am curious to what is causing the aforementioned error. Could you help me out? Thanks in advance

**Comment by roysbike** [comment]
`[5/20/2020, 10:55:37 PM] TypeError: Cannot read property 'get_channel' of null
    at /homebridge/node_modules/homebridge-lgtv-2012a/index.js:314:8
    at /homebridge/node_modules/homebridge-lgtv-2012a/index.js:223:5
    at lgtv.new_session (/homebridge/node_modules/homebridge-lgtv-2012a/node_modules/lgtv-2012/index.js:194:20)
    at LGAccessory.connect (/homebridge/node_modules/homebridge-lgtv-2012a/index.js:221:12)
    at LGAccessory.getChannel (/homebridge/node_modules/homebridge-lgtv-2012a/index.js:313:9)
    at ActiveIdentifier.emit (events.js:310:20)
    at ActiveIdentifier.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at ActiveIdentifier.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)`

Homebridge version 1.1.0
